### ISSUE TITLE
根本不行的啊  

### ISSUE THREAD

**Issue by hinnncom** [NicCraver/electron-print#2]
发出任务 一直返回false

**Comment by yangx14488** [comment]
我觉得这似乎并没有进行真机测试过.....众所周知，electron3以上的版本，存在静默打印问题，一直都没有得到过修复。

**Comment by NicCraver** [comment]
如果回调为false，说明打印机没有连接到，先试试能不能打印一个word

**Comment by NicCraver** [comment]
> 我觉得这似乎并没有进行真机测试过.....众所周知，electron3以上的版本，存在静默打印问题，一直都没有得到过修复。

抱歉之前没有看到你的留言，相信我，方法是经过测试可行的！

**Comment by hinnncom** [comment]
> 发出任务 一直返回false
